/**
 * Seed six weekly search preferences for existing teams with no preferences or
 * generated search reports. Teams with any existing report setup are skipped.
 * Preview: npx ts-node src/scripts/backfillTeamSearchPreferences.ts --dry-run
 * Write:   npx ts-node src/scripts/backfillTeamSearchPreferences.ts --apply
 *
 * Apply requires MongoDB transaction support (replica set or sharded cluster).
 * Each team's six preferences commit together. Report results are generated by
 * the existing scheduler; this script does not generate results or send alerts.
 */
import crypto from 'crypto';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import TeamProfile from '../modules/profiles/team/model/TeamModel';
import SearchPreferences from '../modules/search-preferences/models/SearchPreferences';
import SearchReport from '../modules/search-preferences/models/SearchReport';
import { buildDefaultTeamSearchPreferences, DEFAULT_TEAM_SEARCH_PREFERENCE_COUNT } from '../modules/search-preferences/utils/defaultTeamSearchPreferences';

export { buildDefaultTeamSearchPreferences } from '../modules/search-preferences/utils/defaultTeamSearchPreferences';

export async function backfillTeamSearchPreferences(apply = false) {
  // Native reads avoid implicit collection/index creation during previews.
  const teams = mongoose.connection.collection(TeamProfile.collection.name);
  const preferences = mongoose.connection.collection(SearchPreferences.collection.name);
  const reports = mongoose.connection.collection(SearchReport.collection.name);
  const stats = { scanned: 0, eligible: 0, skippedExisting: 0, skippedChanged: 0, teamsSeeded: 0, inserted: 0 };
  const cursor = teams.find({}, { projection: { _id: 1, name: 1 } });
  let session: mongoose.ClientSession | undefined;

  const hasExistingReports = async (ownerId: mongoose.Types.ObjectId, activeSession?: mongoose.ClientSession) => {
    const filter = { ownerType: 'team', ownerId };
    const options = { projection: { _id: 1 }, ...(activeSession ? { session: activeSession } : {}) };
    // Transaction operations must run sequentially on the session.
    return !!(await preferences.findOne(filter, options)) || !!(await reports.findOne(filter, options));
  };

  try {
    if (apply) session = await mongoose.startSession();
    for await (const team of cursor) {
      stats.scanned += 1;
      if (!(team._id instanceof mongoose.Types.ObjectId)) {
        throw new Error('Team profile ID must be an ObjectId');
      }
      if (await hasExistingReports(team._id)) {
        stats.skippedExisting += 1;
        continue;
      }
      stats.eligible += 1;
      console.info(JSON.stringify({ teamId: team._id, name: team.name, preferencesToInsert: DEFAULT_TEAM_SEARCH_PREFERENCE_COUNT }));
      if (!apply) continue;

      const now = new Date();
      const documents = await Promise.all(buildDefaultTeamSearchPreferences(team._id).map(async data => {
        // Stable IDs and the built-in _id index prevent two concurrent script
        // runs from inserting duplicate sets without changing any indexes.
        const key = `team-default-search-preferences:v1:${team._id}:${data.name}`;
        const id = crypto.createHash('sha256').update(key).digest('hex').slice(0, 24);
        const _id = new mongoose.Types.ObjectId(id);
        const preference = new SearchPreferences({
          ...data, _id, createdAt: now, updatedAt: now, __v: 0,
        });
        await preference.validate();
        // Keep empty performanceMetrics as {}, and persist BSON-ready values.
        return { ...preference.toObject({ flattenMaps: true, minimize: false }), _id };
      }));

      let inserted = false;
      try {
        inserted = (await session!.withTransaction(async () => {
          if (await hasExistingReports(team._id, session)) return false;
          await preferences.insertMany(documents, { session, ordered: true });
          return true;
        }, { readConcern: { level: 'snapshot' }, writeConcern: { w: 'majority' } })) === true;
      } catch (error) {
        // Another script run may have committed the same stable IDs first.
        if ((error as { code?: number }).code !== 11000 || !(await hasExistingReports(team._id))) throw error;
      }

      if (inserted) {
        stats.teamsSeeded += 1;
        stats.inserted += documents.length;
      } else {
        stats.skippedChanged += 1;
      }
    }
  } finally {
    try {
      await cursor.close();
    } finally {
      await session?.endSession();
    }
  }

  return { mode: apply ? 'apply' : 'dry-run', plannedPreferences: stats.eligible * DEFAULT_TEAM_SEARCH_PREFERENCE_COUNT, ...stats };
}

async function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help')) {
    console.info('Usage: npx ts-node src/scripts/backfillTeamSearchPreferences.ts [--dry-run | --apply]');
    console.info('Apply requires a MongoDB replica set or sharded cluster. Run one backfill while manual team report creation is paused.');
    return;
  }
  if (args.some(arg => !['--dry-run', '--apply'].includes(arg)) ||
      (args.includes('--dry-run') && args.includes('--apply'))) {
    throw new Error('Choose --dry-run (default) or --apply');
  }

  dotenv.config();
  const { MONGO_URI, MONGO_USER, MONGO_PASS, CLUSTER_STRING, MONGO_DBNAME } = process.env;
  if (!MONGO_URI && (!MONGO_USER || !MONGO_PASS || !CLUSTER_STRING)) {
    throw new Error('Set MONGO_URI or MONGO_USER, MONGO_PASS, and CLUSTER_STRING');
  }
  const uri = MONGO_URI || `mongodb+srv://${encodeURIComponent(MONGO_USER!)}:${encodeURIComponent(MONGO_PASS!)}@${CLUSTER_STRING}/?retryWrites=true&w=majority`;

  try {
    await mongoose.connect(uri, {
      ...(MONGO_DBNAME ? { dbName: MONGO_DBNAME } : {}),
      autoIndex: false,
      autoCreate: false,
    });
    console.info(JSON.stringify(await backfillTeamSearchPreferences(args.includes('--apply')), null, 2));
  } finally {
    await mongoose.disconnect();
  }
}

if (require.main === module) {
  main().catch(() => {
    // Connection errors may contain credentials; do not print the URI or error.
    console.error('Team search preference backfill failed. Check arguments, database configuration, and transaction support. Completed teams can be safely skipped on rerun.');
    process.exitCode = 1;
  });
}
