import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { JobPostModel } from '../modules/jobs/models/JobPost';

dotenv.config();

const TEAM_ID = '689de192258d32dd996d6726';
const CREATED_BY = '688ba79450f50149ccb8035f';

const seedJobs = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI as string);
    console.info('🔗 Connected to MongoDB');

    const now = new Date();
    const expiresIn = (days: number): Date => {
      const d = new Date(now);
      d.setDate(d.getDate() + days);
      return d;
    };

    const jobs = [
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'General Manager',
        department: 'Operations',
        experienceLevel: 'senior',
        industries: ['professional sports', 'sports management'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Dallas', state: 'TX', country: 'US' },
        description: 'Lead all team operations, player personnel decisions, and strategic planning for a competitive professional sports franchise.',
        requirements: [
          '8+ years of experience in professional sports management',
          'Proven track record in roster building and salary cap management',
          'Strong leadership and negotiation skills',
          'Experience working with coaches, scouts, and front office staff',
        ],
        preferredQualifications: ['Prior GM or AGM experience at the professional level', 'Law or MBA degree', 'Established relationships in the league network'],
        status: 'published',
        expiresAt: expiresIn(75),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Director of Player Personnel',
        department: 'Scouting',
        experienceLevel: 'executive',
        industries: ['professional sports', 'player development'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Dallas', state: 'TX', country: 'US' },
        description: 'Oversee all scouting operations, draft preparation, and free agency evaluation. Collaborate with the GM and coaching staff on roster decisions.',
        requirements: [
          '10+ years of scouting or player personnel experience',
          'Deep knowledge of the draft process and player evaluation',
          'Excellent communication skills across all levels of the organization',
          'Ability to manage and develop a scouting staff',
        ],
        preferredQualifications: ['Prior experience as a scout or player at the professional level', 'Proficiency with scouting software and video tools'],
        status: 'published',
        expiresAt: expiresIn(80),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Head Coach',
        department: 'Coaching',
        experienceLevel: 'senior',
        industries: ['professional sports', 'athletics'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Miami', state: 'FL', country: 'US' },
        description: 'Lead the coaching staff in game planning, practice management, and player development. Represent the organization publicly with professionalism.',
        requirements: [
          '5+ years of head coaching experience at the professional or collegiate level',
          'Strong ability to develop and manage assistant coaches',
          'Excellent in-game decision-making and adaptability',
          'History of developing players and winning cultures',
        ],
        preferredQualifications: ['Prior playing experience at the professional level', 'Playoff or championship coaching experience'],
        status: 'published',
        expiresAt: expiresIn(60),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Offensive Coordinator',
        department: 'Coaching',
        experienceLevel: 'mid',
        industries: ['professional sports', 'athletics'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Miami', state: 'FL', country: 'US' },
        description: 'Design and implement offensive schemes. Mentor position coaches and work directly with skill position players to maximize production.',
        requirements: [
          '3+ years of experience as an offensive coordinator or position coach',
          'Proficiency in film review and play design',
          'Strong communication skills with players and coaching staff',
        ],
        preferredQualifications: ['History of developing high-performance offenses', 'Experience with multiple offensive systems'],
        status: 'published',
        expiresAt: expiresIn(65),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Operations Manager',
        department: 'Operations',
        experienceLevel: 'mid',
        industries: ['professional sports', 'sports management'],
        employmentType: 'full_time',
        locationType: 'hybrid',
        location: { city: 'Chicago', state: 'IL', country: 'US' },
        description: 'Manage day-to-day organizational operations including travel logistics, facility coordination, and staff scheduling.',
        requirements: [
          '3+ years of operations management experience',
          'Strong organizational and project management skills',
          'Experience managing vendors and logistics',
          'Proficiency in Microsoft Office and project management tools',
        ],
        preferredQualifications: ['Experience in a professional sports environment', 'PMP or equivalent certification'],
        status: 'published',
        expiresAt: expiresIn(70),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Scout',
        department: 'Scouting',
        experienceLevel: 'entry',
        industries: ['professional sports', 'player development'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'New York', state: 'NY', country: 'US' },
        description: 'Identify and evaluate talent at the collegiate and professional levels. Submit detailed scouting reports and attend live events.',
        requirements: [
          '1+ years of scouting or player evaluation experience',
          'Knowledge of current player talent pool and evaluation criteria',
          'Excellent written and verbal communication',
          'Willingness to travel extensively',
        ],
        preferredQualifications: ['Background in playing or coaching the sport', 'Experience using digital scouting platforms'],
        status: 'published',
        expiresAt: expiresIn(85),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Data Analyst',
        department: 'Analytics',
        experienceLevel: 'mid',
        industries: ['sports analytics', 'professional sports'],
        employmentType: 'full_time',
        locationType: 'remote',
        description: 'Analyze player performance data, opponent tendencies, and league trends to inform front office and coaching decisions.',
        requirements: [
          "Bachelor's degree in Statistics, Data Science, or related field",
          'Proficiency in Python, R, or SQL',
          'Experience building data visualizations and dashboards',
          '2+ years of sports analytics or quantitative analysis experience',
        ],
        preferredQualifications: ['Familiarity with sports-specific data platforms (Synergy, Second Spectrum)', 'Graduate degree in a quantitative field'],
        status: 'published',
        expiresAt: expiresIn(90),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Video Coordinator',
        department: 'Coaching',
        experienceLevel: 'entry',
        industries: ['professional sports', 'athletics'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Seattle', state: 'WA', country: 'US' },
        description: 'Manage video editing and breakdown for opponent scouting and player development. Support the coaching staff with game and practice film.',
        requirements: [
          'Experience with video editing software (Synergy, Hudl, or similar)',
          'Strong attention to detail and organizational skills',
          'Ability to work long hours during the season',
          'Knowledge of the game at a competitive level',
        ],
        preferredQualifications: ['Prior experience in a professional or collegiate video department', 'Experience managing video databases'],
        status: 'published',
        expiresAt: expiresIn(60),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Athletic Trainer',
        department: 'Medical',
        experienceLevel: 'mid',
        industries: ['professional sports', 'athletics', 'sports management'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Los Angeles', state: 'CA', country: 'US' },
        description: 'Provide injury prevention, evaluation, rehabilitation, and return-to-play clearance for players. Coordinate with team physicians and strength staff.',
        requirements: [
          'Board Certified Athletic Trainer (ATC) credential required',
          '3+ years of athletic training experience in competitive sports',
          'Knowledge of injury rehabilitation protocols',
          'Experience in a team setting with multi-player caseloads',
        ],
        preferredQualifications: ["Master's degree in Athletic Training or Kinesiology", 'Professional sports experience'],
        status: 'published',
        expiresAt: expiresIn(72),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Marketing Manager',
        department: 'Marketing',
        experienceLevel: 'mid',
        industries: ['professional sports', 'sports management'],
        employmentType: 'full_time',
        locationType: 'hybrid',
        location: { city: 'Atlanta', state: 'GA', country: 'US' },
        description: 'Lead marketing campaigns, brand partnerships, and fan engagement initiatives. Oversee digital, print, and experiential marketing channels.',
        requirements: [
          '4+ years of marketing experience',
          'Proven ability to manage cross-channel campaigns',
          'Strong project management and communication skills',
          'Experience with CRM, email marketing, and digital advertising platforms',
        ],
        preferredQualifications: ['Background in sports or entertainment marketing', 'Experience managing marketing budgets of $500K+'],
        status: 'published',
        expiresAt: expiresIn(75),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Director of Analytics',
        department: 'Analytics',
        experienceLevel: 'senior',
        industries: ['sports analytics', 'professional sports'],
        employmentType: 'full_time',
        locationType: 'remote',
        description: 'Build and lead the analytics function. Develop models for player evaluation, game strategy, and organizational decision-making.',
        requirements: [
          '6+ years of analytics experience with progressive leadership responsibility',
          'Expert-level proficiency in Python or R and SQL',
          'Demonstrated ability to communicate complex analysis to non-technical stakeholders',
          'Experience managing a team of analysts',
        ],
        preferredQualifications: [
          "Ph.D. or Master's in Statistics, Computer Science, or related discipline",
          'Track record of driving decision-making with data at a professional sports organization',
        ],
        status: 'published',
        expiresAt: expiresIn(90),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Team Operations Intern',
        department: 'Operations',
        experienceLevel: 'student',
        industries: ['professional sports', 'sports management'],
        employmentType: 'internship',
        locationType: 'onsite',
        location: { city: 'Denver', state: 'CO', country: 'US' },
        description: 'Support the operations department with logistics coordination, equipment tracking, and administrative tasks during the season.',
        requirements: ['Currently enrolled in a college or university program', 'Strong organizational and time-management skills', 'Team-oriented mindset and eagerness to learn'],
        preferredQualifications: ['Sports management, business, or kinesiology major', 'Prior sports internship experience'],
        status: 'published',
        expiresAt: expiresIn(60),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Contract Scout',
        department: 'Scouting',
        experienceLevel: 'entry',
        industries: ['professional sports', 'player development'],
        employmentType: 'contract',
        locationType: 'remote',
        description: 'Evaluate assigned player pool on a contract basis. Deliver detailed reports using our standardized scouting template.',
        requirements: [
          'Experience evaluating players at the collegiate or professional level',
          'Ability to submit reports within defined deadlines',
          'Strong written evaluation skills',
        ],
        preferredQualifications: ['Prior playing or coaching background', 'Familiarity with video-based scouting tools'],
        status: 'published',
        expiresAt: expiresIn(65),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Strength and Conditioning Coach',
        department: 'Medical',
        experienceLevel: 'mid',
        industries: ['professional sports', 'athletics', 'player development'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Chicago', state: 'IL', country: 'US' },
        description: 'Design and implement individualized and team-wide strength, conditioning, and recovery programs throughout the season and off-season.',
        requirements: [
          'NSCA CSCS or equivalent certification required',
          '3+ years of strength and conditioning experience in competitive sports',
          'Knowledge of periodization and sports science principles',
          'Ability to collaborate with medical and coaching staff',
        ],
        preferredQualifications: ['Professional or high-level collegiate experience', "Master's in Exercise Science or related field"],
        status: 'published',
        expiresAt: expiresIn(70),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Social Media Coordinator',
        department: 'Marketing',
        experienceLevel: 'entry',
        industries: ['professional sports', 'sports management'],
        employmentType: 'part_time',
        locationType: 'remote',
        description: 'Create, schedule, and manage content across all team social media channels. Engage fans and grow the brand digital footprint.',
        requirements: [
          'Experience managing social media accounts professionally or in a university setting',
          'Proficiency with Instagram, X (Twitter), TikTok, and Facebook',
          'Basic photo and video editing skills',
          'Strong writing voice and attention to trends',
        ],
        preferredQualifications: ['Experience with social media management tools (Sprout, Hootsuite)', 'Background in sports or entertainment content creation'],
        status: 'published',
        expiresAt: expiresIn(80),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Equipment Manager',
        department: 'Operations',
        experienceLevel: 'entry',
        industries: ['professional sports', 'athletics'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Dallas', state: 'TX', country: 'US' },
        description: 'Manage all team equipment including ordering, inventory, travel packing, and maintenance of facilities and gear.',
        requirements: [
          'Prior experience in equipment management at the collegiate or professional level',
          'Strong organizational skills and ability to manage inventory systems',
          'Willingness to work early mornings, late nights, and travel with the team',
        ],
        preferredQualifications: ['Professional athletic equipment management certification', 'Experience with large equipment inventories'],
        status: 'published',
        expiresAt: expiresIn(62),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Assistant Coach',
        department: 'Coaching',
        experienceLevel: 'entry',
        industries: ['professional sports', 'athletics', 'player development'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'Seattle', state: 'WA', country: 'US' },
        description: 'Support the head coach and coordinator staff with practice planning, film review, and player skill development sessions.',
        requirements: [
          '1+ years of coaching experience at any competitive level',
          'Strong knowledge of the game and ability to teach fundamentals',
          'Collaborative mindset and willingness to take on diverse responsibilities',
        ],
        preferredQualifications: ['Playing experience at the collegiate or professional level', 'Prior experience under a structured coaching staff'],
        status: 'published',
        expiresAt: expiresIn(68),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Player Relations Manager',
        department: 'Operations',
        experienceLevel: 'mid',
        industries: ['professional sports', 'sports management', 'player development'],
        employmentType: 'full_time',
        locationType: 'onsite',
        location: { city: 'New York', state: 'NY', country: 'US' },
        description: 'Serve as the primary liaison between players and the front office. Support player transitions, community programs, and off-field needs.',
        requirements: [
          '3+ years of experience in player relations, human resources, or athlete services',
          'Excellent interpersonal and conflict resolution skills',
          'Discretion and ability to handle sensitive information professionally',
        ],
        preferredQualifications: ['Prior playing experience or athletic background', 'Background in counseling, social work, or HR'],
        status: 'published',
        expiresAt: expiresIn(78),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Performance Analyst',
        department: 'Analytics',
        experienceLevel: 'entry',
        industries: ['sports analytics', 'professional sports', 'player development'],
        employmentType: 'full_time',
        locationType: 'hybrid',
        location: { city: 'Los Angeles', state: 'CA', country: 'US' },
        description: 'Collect, organize, and present player performance data to coaches and front office staff. Support development of tracking and reporting systems.',
        requirements: [
          "Bachelor's degree in Sports Science, Statistics, or related field",
          'Experience with data collection tools and spreadsheet analysis',
          'Ability to communicate findings clearly in written and visual formats',
        ],
        preferredQualifications: ['Familiarity with GPS tracking or wearables data', 'Prior internship in a sports analytics department'],
        status: 'published',
        expiresAt: expiresIn(75),
      },
      {
        team: TEAM_ID,
        createdBy: CREATED_BY,
        title: 'Recruiting Coordinator',
        department: 'Scouting',
        experienceLevel: 'mid',
        industries: ['professional sports', 'player development', 'sports management'],
        employmentType: 'full_time',
        locationType: 'hybrid',
        location: { city: 'Atlanta', state: 'GA', country: 'US' },
        description: 'Coordinate recruiting outreach, manage prospect databases, and assist the scouting department in organizing draft boards and evaluation timelines.',
        requirements: [
          '2+ years of experience in recruiting, talent acquisition, or scouting coordination',
          'Strong database and CRM management skills',
          'Excellent communication and scheduling abilities',
          'Ability to manage multiple priorities during high-volume recruiting periods',
        ],
        preferredQualifications: ['Experience in a professional sports front office or collegiate athletics department', 'Familiarity with ATS or scouting management platforms'],
        status: 'published',
        expiresAt: expiresIn(83),
      },
    ];

    await JobPostModel.insertMany(jobs);
    console.info(`✅ Inserted ${jobs.length} job posts`);
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.info('🔌 Disconnected from MongoDB');
  }
};

seedJobs();
